// themes.js
const themes = {
    'Arta si Cultura': { representativeTheme: 'Artă și Cultură', displayName: 'Artă și Cultură' },
    'Afaceri': { representativeTheme: 'Afaceri', displayName: 'Afaceri' },
    'Artă/Cultură': { representativeTheme: 'Artă și Cultură', displayName: 'Artă și Cultură' },
    'Dezvoltare': { representativeTheme: 'Dezvoltare', displayName: 'Dezvoltare' },
    'Drepturile Animalelor': { representativeTheme: 'Drepturile Animalelor', displayName: 'Drepturile Animalelor' },
    'Familie': { representativeTheme: 'Familie', displayName: 'Familie' },
    'Feminism': { representativeTheme: 'Feminism', displayName: 'Feminism' },
    'Istorie': { representativeTheme: 'Istorie', displayName: 'Istorie' },
    'LGBT+': { representativeTheme: 'LGBT+', displayName: 'LGBT+' },
    'LOL': { representativeTheme: 'LOL', displayName: 'LOL' },
    'Moralitate': { representativeTheme: 'Moralitate', displayName: 'Moralitate' },
    'Politici Sociale': { representativeTheme: 'Politici Sociale', displayName: 'Politici Sociale' },
    'Sport': { representativeTheme: 'Sport', displayName: 'Sport' },
    'Terorism': { representativeTheme: 'Terorism', displayName: 'Terorism' },
    'Trenduri Sociale': { representativeTheme: 'Trenduri Sociale', displayName: 'Trenduri Sociale' },
    'Religie': { representativeTheme: 'Religie', displayName: 'Religie' },
    'SF': { representativeTheme: 'SF', displayName: 'SF' },
    'Relații/Cupluri': { representativeTheme: 'Relații/Cupluri', displayName: 'Relații/Cupluri' },
    'Mass/Social Media': { representativeTheme: 'Mass/Social Media', displayName: 'Mass/Social Media' },
    'Mediu': { representativeTheme: 'Mediu', displayName: 'Mediu' },
    'Economie': { representativeTheme: 'Economie și Finanțe', displayName: 'Economie și Finanțe' },
    'Economie/Finance': { representativeTheme: 'Economie și Finanțe', displayName: 'Economie și Finanțe' },
    'Educatie': { representativeTheme: 'Educație', displayName: 'Educație' },
    'Educație': { representativeTheme: 'Educație', displayName: 'Educație' },
    'Experienta Umana?': { representativeTheme: 'Experiență Umană', displayName: 'Experiență Umană' },
    'Experiența Umană': { representativeTheme: 'Experiență Umană', displayName: 'Experiență Umană' },
    'Justitie': { representativeTheme: 'Justiție', displayName: 'Justiție' },
    'Justiție': { representativeTheme: 'Justiție', displayName: 'Justiție' },
    'Libertati': { representativeTheme: 'Libertăți', displayName: 'Libertăți' },
    'Libertăți': { representativeTheme: 'Libertăți', displayName: 'Libertăți' },
    'Medicina': { representativeTheme: 'Medicină', displayName: 'Medicină' },
    'Medicină': { representativeTheme: 'Medicină', displayName: 'Medicină' },
    'Minoritati': { representativeTheme: 'Minorități', displayName: 'Minorități' },
    'Minorități': { representativeTheme: 'Minorități', displayName: 'Minorități' },
    'Politică': { representativeTheme: 'Politică', displayName: 'Politică' },
    'Politica': { representativeTheme: 'Politică', displayName: 'Politică' },
    'Relatii Internationale': { representativeTheme: 'Relații Internaționale', displayName: 'Relații Internaționale' },
    'Relații Internaționale': { representativeTheme: 'Relații Internaționale', displayName: 'Relații Internaționale' },
    'Securitate Razboi si Armata': { representativeTheme: 'Securitate, Război și Armată', displayName: 'Securitate, Război și Armată' },
    'Securitate/Război/Armată': { representativeTheme: 'Securitate, Război și Armată', displayName: 'Securitate, Război și Armată' },
    'Știință și Tehnologie': { representativeTheme: 'Știință și Tehnologie', displayName: 'Știință și Tehnologie' },
    'Stiinta si tehnologie': { representativeTheme: 'Știință și Tehnologie', displayName: 'Știință și Tehnologie' }
};

// Export the themes object
export default themes;
